[build]
  publish = "public"
  command = "hugo --gc --minify && cp robots.production.txt public/robots.txt"

[build.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --buildFuture && cp robots.staging.txt public/robots.txt"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.141.0"
  HUGO_BUILD_DRAFTS = "true"
  HUGO_BUILD_EXPIRED = "false"

[context.branch-deploy]
  command = "hugo --gc --buildFuture && cp robots.staging.txt public/robots.txt"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.141.0"
  HUGO_BUILD_DRAFTS = "true"
  HUGO_BUILD_EXPIRED = "false"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
